export const iconCss=`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">`;
export const css=`
:root{--bg:#f6f8fc;--card:#fff;--text:#172033;--muted:#64748b;--line:#e2e8f0;--blue:#1a73e8;--green:#188038;--red:#d93025}
*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Segoe UI",Arial,sans-serif;background:var(--bg);color:var(--text);direction:rtl}
.app{display:grid;grid-template-columns:220px 1fr;min-height:100vh}.side{background:#fff;border-left:1px solid var(--line);padding:18px 12px}.brand{font-size:22px;font-weight:800;padding:0 10px 18px}.nav button{width:100%;border:0;background:transparent;text-align:right;padding:11px 12px;border-radius:12px;font-weight:650;cursor:pointer}.nav button.active,.nav button:hover{background:#e8f0fe;color:#174ea6}.main{padding:22px;min-width:0}.top{display:flex;align-items:center;justify-content:space-between;gap:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.card,.panel{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px;margin-top:14px}.metric{font-size:28px;font-weight:800}.muted{color:var(--muted);font-size:13px}.row{display:flex;gap:10px;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);padding:10px 0}.row:last-child{border:0}.btn{border:0;border-radius:9px;padding:9px 12px;font-weight:700;cursor:pointer;background:#eef2f7}.btn.primary{background:var(--blue);color:#fff}.btn.green{background:#e6f4ea;color:var(--green)}.btn.red{background:#fce8e6;color:var(--red)}input,textarea,select{width:100%;border:1px solid #cbd5e1;border-radius:9px;padding:10px;font:inherit}textarea{min-height:110px}.field{margin:10px 0}.conversation{max-height:55vh;overflow:auto}.bubble{max-width:78%;padding:10px 12px;border-radius:14px;margin:8px 0;background:#f1f5f9;white-space:pre-wrap}.bubble.out{margin-right:auto;background:#e8f0fe}.draft{background:#fff8e1;border:1px solid #f7d774}.tag{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef2f7;font-size:11px}.status-ok{color:var(--green)}.status-bad{color:var(--red)}
.login{width:min(420px,92vw);margin:14vh auto;background:#fff;border:1px solid var(--line);border-radius:18px;padding:28px;box-shadow:0 20px 45px #0f172a14}.login h1{margin:0 0 22px;text-align:center;font-size:28px}.password-wrap{position:relative}.password-wrap input{padding-left:48px;direction:ltr;text-align:left}.password-toggle{position:absolute;left:5px;top:50%;transform:translateY(-50%);width:40px;height:40px;border:0;border-radius:9px;background:transparent;color:#475569;cursor:pointer;font-size:19px}.password-toggle:hover{background:#f1f5f9}.login-error{background:#fef2f2;border:1px solid #fecaca;color:#991b1b;padding:10px 12px;border-radius:10px;margin:0 0 12px;font-size:14px}.security-page{text-align:center}.security-icon{font-size:42px;color:#b91c1c;margin-bottom:10px}
@media(max-width:800px){.app{grid-template-columns:70px 1fr}.brand{font-size:0}.brand:after{content:"A";font-size:24px}.nav button span{display:none}.main{padding:12px}}
`;
function documentHead(title="Aharon CRM"){return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title>${iconCss}<style>${css}</style>`;}
export function loginHtml({error=""}={}){return `<!doctype html><html lang="he" dir="rtl"><head>${documentHead()}</head><body><div class="login"><h1>Aharon CRM</h1>${error?`<div class="login-error" role="alert">${error}</div>`:""}<form method="post" action="/login"><div class="field password-wrap"><input id="crmPassword" type="password" name="password" placeholder="סיסמה" autocomplete="current-password" required autofocus><button id="togglePassword" class="password-toggle" type="button" aria-label="הצג סיסמה" title="הצג סיסמה"><i class="bi bi-eye" aria-hidden="true"></i></button></div><button class="btn primary" style="width:100%">כניסה</button></form></div><script>const input=document.getElementById('crmPassword'),button=document.getElementById('togglePassword'),icon=button.querySelector('i');button.addEventListener('click',()=>{const show=input.type==='password';input.type=show?'text':'password';icon.className=show?'bi bi-eye-slash':'bi bi-eye';button.setAttribute('aria-label',show?'הסתר סיסמה':'הצג סיסמה');button.title=show?'הסתר סיסמה':'הצג סיסמה';input.focus();});</script></body></html>`;}
export function lockedHtml(){return `<!doctype html><html lang="he" dir="rtl"><head>${documentHead()}</head><body><div class="login security-page"><div class="security-icon"><i class="bi bi-shield-lock"></i></div><h1>Aharon CRM</h1><p>המערכת נעולה זמנית מסיבות אבטחה.</p><p class="muted">נדרשת בדיקה ידנית לפני פתיחת הגישה מחדש.</p></div></body></html>`;}
export function blockedHtml(){return `<!doctype html><html lang="he" dir="rtl"><head>${documentHead()}</head><body><div class="login security-page"><div class="security-icon"><i class="bi bi-slash-circle"></i></div><h1>הגישה נחסמה</h1><p>כתובת הרשת הזו חסומה במערכת.</p></div></body></html>`;}
export function appHtml(){return `<!doctype html><html lang="he" dir="rtl"><head>${documentHead()}<style>
label{display:block;margin:12px 0}dialog{width:min(650px,95vw);max-height:90vh;overflow:auto;border:1px solid #ddd;border-radius:16px}dialog::backdrop{background:#0006}.error{color:#b91c1c;white-space:pre-wrap}.actions{display:flex;gap:8px;flex-wrap:wrap}.note{white-space:pre-wrap}.row>div{min-width:0}.row .actions{justify-content:flex-end}.row{flex-wrap:wrap}.settings-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.chat-log{max-height:55vh;overflow:auto}.chat-log .bubble{overflow-wrap:anywhere}.source-list{font-size:12px;color:var(--muted)}.nav .bi{font-size:18px;margin-inline-end:7px}.danger-zone{border-color:#fecaca}.setting-help{font-size:13px;color:var(--muted)}.file-preview{white-space:pre-wrap;max-height:45vh;overflow:auto;direction:auto}.top h1{font-size:clamp(20px,4vw,30px)}.btn{min-height:40px}.panel h2{font-size:18px}.form-inline{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.form-inline label{flex:1;min-width:170px}.empty{padding:24px;color:#64748b}.nav button{min-height:44px}.bubble{overflow-wrap:anywhere}button:disabled{opacity:.5;cursor:wait}
</style></head><body><div class="app"><aside class="side"><div class="brand">Aharon CRM</div><nav class="nav" aria-label="ניווט ראשי">
${[["home", "house", "ראשי"], ["assistant", "stars", "העוזר האישי"], ["inbox", "inbox", "תיבת הודעות"], ["spam", "shield-exclamation", "דואר זבל"], ["suggestions", "lightbulb", "הצעות חכמות"], ["reminders", "alarm", "תזכורות"], ["notifications", "bell", "התראות"], ["clients", "people", "לקוחות"], ["projects", "kanban", "פרויקטים"], ["tasks", "check2-square", "משימות"], ["systems", "telephone", "מערכות"], ["accounts", "person-badge", "חשבונות"], ["files", "folder2", "קבצים"], ["connectors", "plug", "חיבורים"], ["ai", "cpu", "בינה מלאכותית"], ["settings", "gear", "הגדרות"]].map(([v,i,label])=>`<button data-view="${v}" title="${label}" aria-label="${label}"><i class="bi bi-${i}" aria-hidden="true"></i> <span>${label}</span></button>`).join("")}
</nav></aside><main class="main"><div class="top"><h1 id="title">Aharon CRM</h1><form method="post" action="/logout"><button class="btn">יציאה</button></form></div><p id="notice" role="status"></p><p id="error" class="error" role="alert"></p><div id="content"></div></main></div><dialog id="editor"><form id="editForm"><h2 id="editTitle"></h2><div id="fields"></div><p id="editError" class="error"></p><div class="actions"><button class="btn primary" type="submit">שמירה</button><button class="btn" type="button" data-action="close-editor">ביטול</button></div></form></dialog><script src="/assets/app.js" defer></script></body></html>`;}
